# Usa la imagen oficial de Bun
FROM oven/bun:latest

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia solo los archivos esenciales primero (mejora la caché de Docker)
COPY package.json ./

# Instala las dependencias con Bun
RUN bun install --frozen-lockfile

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto en el que corre el backend
EXPOSE 5500

# Comando para iniciar el servidor
CMD ["bun", "run", "start"]
